# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

version: "3.7"

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy

services:
  jawanndenn:
    build: .
    networks:
      - traefik_proxy
    labels:
      traefik.enable: "true"
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:poll.${DOMAINNAME}"
      traefik.port: "8080"
      traefik.docker.network: "traefik_proxy"
    volumes:
      - ~/.jawanndenn-docker/:/data
    restart: always
